server:
  http:
    port: 8080

database:
  postgres:
    host: $DB_HOST
    port: $DB_PORT
    database: $DB_NAME
    user: $DB_USER
    password: $DB_PASSWORD
    ssl:
      mode: require

firstInstance:
  orgName: MyOrganization
  org:
    human:
      username: admin
      password: $ADMIN_PASSWORD

externalSecure: true
externalHost: $EXTERNAL_HOST
