server:
  http:
    port: 8080

database:
  postgres:
    host: ${ZITADEL_DATABASE_POSTGRES_HOST}
    port: ${ZITADEL_DATABASE_POSTGRES_PORT}
    database: ${ZITADEL_DATABASE_POSTGRES_DATABASE}
    user: ${ZITADEL_DATABASE_POSTGRES_USER}
    password: ${ZITADEL_DATABASE_POSTGRES_PASSWORD}
    ssl:
      mode: require

firstInstance:
  orgName: MyOrganization
  org:
    human:
      username: admin
      password: ${ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD}

externalSecure: true
externalHost: ${ZITADEL_EXTERNALHOST}
